services:
  - type: web
    name: ProdX
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    packages:
      - google-chrome-stable
